version: '3.9'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest  # ? alterado
    container_name: sqlserver_cantina
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrong@Password1
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    restart: unless-stopped

volumes:
  sqlserver_data:
